version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/go/src/app'
      - '/go/src/app/vendor'
    environment:
      PORT: 9800
    ports:
      - '9800:9800'
    command: /go/bin/myapp