version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/go/src/github.com/miyanokomiya/gogollellero'
    environment:
      PORT: 8080
      CLIENT_HOST: 'http://localhost:3000' # cors対応用
    ports:
      - '8080:8080'
    command: bash -c "dep ensure && GO_ENV=development gin -p 8080"
    container_name: gogollellero_web
    links:
      - db:gogollellero_db
    tty: true
  db:
    image: mysql:5.7
    volumes:
      - './.db:/var/lib/mysql'
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: miyanokomiya
        MYSQL_PASSWORD: miyanokomiya
        MYSQL_DATABASE: gogollellero
    ports:
      - '3306:3306'
    container_name: gogollellero_db
