version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/go/src/github.com/miyanokomiya/gogollellero'
      - '/go/src/github.com/miyanokomiya/gogollellero/vendor'
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    command: gin -p 8080