driver: mysql
protocol: tcp(gogollellero_db:3306)
development:
  user: miyanokomiya
  password: miyanokomiya
  db: gogollellero
test:
  user: miyanokomiya
  password: miyanokomiya
  db: gogollellero_test
